/*
 * Copyright (c) 2017 Pantacor Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

typedef enum thttp_method {
	THTTP_METHOD_GET = 1,
	THTTP_METHOD_POST,
	THTTP_METHOD_PUT,
	THTTP_METHOD_PATCH,
	THTTP_METHOD_DELETE,
	THTTP_METHOD_HEAD,
	THTTP_METHOD_OPTIONS,
	THTTP_METHOD_UNKNOWN = 1000000,
} thttp_method_t;

typedef enum thttp_proto {
	THTTP_PROTO_HTTP = 1,
	THTTP_PROTO_UNKNOWN = 1000000,
} thttp_proto_t;

typedef enum thttp_proto_version {
	THTTP_PROTO_VERSION_10 = 1,
	THTTP_PROTO_VERSION_11,
	THTTP_PROTO_VERSION_UNKNOWN = 1000000,
} thttp_proto_version_t;

typedef enum thttp_status {
	THTTP_STATUS_CONTINUE = 100,
	THTTP_STATUS_SWITCHING_PROTOCOLS = 101,
	THTTP_STATUS_PROCESSING = 102,
	THTTP_STATUS_OK = 200,
	THTTP_STATUS_CREATED = 201,
	THTTP_STATUS_ACCEPTED = 202,
	THTTP_STATUS_NON_AUTHORITATIVE_INFORMATION = 203,
	THTTP_STATUS_NO_CONTENT = 204,
	THTTP_STATUS_RESET_CONTENT = 205,
	THTTP_STATUS_PARTIAL_CONTENT = 206,
	THTTP_STATUS_MULTI_STATUS = 207,
	THTTP_STATUS_MULTIPLE_CHOICES = 300,
	THTTP_STATUS_MOVED_PERMANENTLY = 301,
	THTTP_STATUS_FOUND = 302,
	THTTP_STATUS_SEE_OTHER = 303,
	THTTP_STATUS_NOT_MODIFIED = 304,
	THTTP_STATUS_USE_PROXY = 305,
	THTTP_STATUS_SWITCH_PROXY = 306,
	THTTP_STATUS_TEMPORARY_REDIRECT = 307,
	THTTP_STATUS_BAD_REQUEST = 400,
	THTTP_STATUS_UNAUTHORIZED = 401,
	THTTP_STATUS_PAYMENT_REQUIRED = 402,
	THTTP_STATUS_FORBIDDEN = 403,
	THTTP_STATUS_NOT_FOUND = 404,
	THTTP_STATUS_METHOD_NOT_ALLOWED = 405,
	THTTP_STATUS_NOT_ACCEPTABLE = 406,
	THTTP_STATUS_METHOD_NOT_ACCEPTABLE = 406, /** deprecated */
	THTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED = 407,
	THTTP_STATUS_REQUEST_TIMEOUT = 408,
	THTTP_STATUS_CONFLICT = 409,
	THTTP_STATUS_GONE = 410,
	THTTP_STATUS_LENGTH_REQUIRED = 411,
	THTTP_STATUS_PRECONDITION_FAILED = 412,
	THTTP_STATUS_REQUEST_ENTITY_TOO_LARGE = 413,
	THTTP_STATUS_REQUEST_URI_TOO_LONG = 414,
	THTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415,
	THTTP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE = 416,
	THTTP_STATUS_EXPECTATION_FAILED = 417,
	THTTP_STATUS_UNPROCESSABLE_ENTITY = 422,
	THTTP_STATUS_LOCKED = 423,
	THTTP_STATUS_FAILED_DEPENDENCY = 424,
	THTTP_STATUS_UNORDERED_COLLECTION = 425,
	THTTP_STATUS_UPGRADE_REQUIRED = 426,
	THTTP_STATUS_NO_RESPONSE = 444,
	THTTP_STATUS_RETRY_WITH = 449,
	THTTP_STATUS_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450,
	THTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = 451,
	THTTP_STATUS_INTERNAL_SERVER_ERROR = 500,
	THTTP_STATUS_NOT_IMPLEMENTED = 501,
	THTTP_STATUS_BAD_GATEWAY = 502,
	THTTP_STATUS_SERVICE_UNAVAILABLE = 503,
	THTTP_STATUS_GATEWAY_TIMEOUT = 504,
	THTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED = 505,
	THTTP_STATUS_VARIANT_ALSO_NEGOTIATES = 506,
	THTTP_STATUS_INSUFFICIENT_STORAGE = 507,
	THTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED = 509,
	THTTP_STATUS_NOT_EXTENDED = 510,
	THTTP_STATUS_UNKNOWN = 10000000
} thttp_status_t;
